/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DividerOrientation } from "./components/Divider/Divider";
export { DividerOrientation } from "./components/Divider/Divider";
export namespace Components {
    interface DsDivider {
        /**
          * Direction of the divider line. Defaults to 'horizontal'.
          * @default 'horizontal'
         */
        "orientation": DividerOrientation;
    }
}
declare global {
    interface HTMLDsDividerElement extends Components.DsDivider, HTMLStencilElement {
    }
    var HTMLDsDividerElement: {
        prototype: HTMLDsDividerElement;
        new (): HTMLDsDividerElement;
    };
    interface HTMLElementTagNameMap {
        "ds-divider": HTMLDsDividerElement;
    }
}
declare namespace LocalJSX {
    interface DsDivider {
        /**
          * Direction of the divider line. Defaults to 'horizontal'.
          * @default 'horizontal'
         */
        "orientation"?: DividerOrientation;
    }

    interface DsDividerAttributes {
        "orientation": DividerOrientation;
    }

    interface IntrinsicElements {
        "ds-divider": Omit<DsDivider, keyof DsDividerAttributes> & { [K in keyof DsDivider & keyof DsDividerAttributes]?: DsDivider[K] } & { [K in keyof DsDivider & keyof DsDividerAttributes as `attr:${K}`]?: DsDividerAttributes[K] } & { [K in keyof DsDivider & keyof DsDividerAttributes as `prop:${K}`]?: DsDivider[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-divider": LocalJSX.IntrinsicElements["ds-divider"] & JSXBase.HTMLAttributes<HTMLDsDividerElement>;
        }
    }
}
