import type { Config } from '@stencil/core';
import { config as packageConfig } from './stencil.config';

/**
 * Storybook needs component bundles and compiler metadata only. Framework
 * adapters are generated by the coherent package build, not on every story edit.
 */
export const config: Config = {
  ...packageConfig,
  outputTargets: packageConfig.outputTargets?.filter(
    target =>
      target.type === 'docs-json' ||
      target.type === 'dist-custom-elements'
  ),
};
