
import * as d from './proxies';

export const DIRECTIVES = [
  d.DsAccordion,
  d.DsAppShell,
  d.DsBadge,
  d.DsBanner,
  d.DsBarNav,
  d.DsBreadcrumb,
  d.DsButtonFilled,
  d.DsButtonUnfilledIcon,
  d.DsCard,
  d.DsCheckbox,
  d.DsChip,
  d.DsDivider,
  d.DsEmptyState,
  d.DsFade,
  d.DsField,
  d.DsHeader,
  d.DsIcon,
  d.DsInput,
  d.DsLoader,
  d.DsMenu,
  d.DsModal,
  d.DsPagination,
  d.DsPanelNav,
  d.DsPanelTools,
  d.DsRadioGroup,
  d.DsScrollbar,
  d.DsSelect,
  d.DsSettingsSectionCard,
  d.DsShellGradientPicker,
  d.DsShellGradientSwatch,
  d.DsSkeleton,
  d.DsSlider,
  d.DsSurface,
  d.DsTabGroup,
  d.DsTabGroupNav,
  d.DsTable,
  d.DsTag,
  d.DsText,
  d.DsToastProvider,
  d.DsToggle,
  d.DsTooltip
];
