
import * as d from './proxies';

export const DIRECTIVES = [
  d.DsAppShell,
  d.DsBadge,
  d.DsBanner,
  d.DsBarNav,
  d.DsButtonFilled,
  d.DsButtonUnfilled,
  d.DsCard,
  d.DsCardDataVizDonut,
  d.DsCardSetting,
  d.DsCardShellDataViz,
  d.DsChartBar,
  d.DsChartDonut,
  d.DsChartLegend,
  d.DsChartLine,
  d.DsCheckbox,
  d.DsChip,
  d.DsDivider,
  d.DsEmptyState,
  d.DsField,
  d.DsIcon,
  d.DsInput,
  d.DsLoader,
  d.DsMenu,
  d.DsModal,
  d.DsPanelNav,
  d.DsPanelSubNav,
  d.DsPanelTools,
  d.DsRadio,
  d.DsSelect,
  d.DsSelectMulti,
  d.DsShellGradientPicker,
  d.DsShellGradientSwatch,
  d.DsSkeleton,
  d.DsSlider,
  d.DsSwatchPicker,
  d.DsSwitch,
  d.DsTabGroup,
  d.DsTag,
  d.DsText,
  d.DsTooltip,
  d.DsTooltipDataViz
];
