'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsAgentResponse as DsAgentResponseElement, defineCustomElement as defineDsAgentResponse } from "@ds-mo/ui/dist/components/ds-agent-response.js";

export type DsAgentResponseEvents = NonNullable<unknown>;

export const DsAgentResponse: StencilReactComponent<DsAgentResponseElement, DsAgentResponseEvents, Components.DsAgentResponse> = /*@__PURE__*/ createComponent<DsAgentResponseElement, DsAgentResponseEvents, Components.DsAgentResponse>({
    tagName: 'ds-agent-response',
    elementClass: DsAgentResponseElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsAgentResponseEvents,
    defineCustomElement: defineDsAgentResponse
});
