'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsAccordionCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsAccordion as DsAccordionElement, defineCustomElement as defineDsAccordion } from "@ds-mo/ui/dist/components/ds-accordion.js";

export type DsAccordionEvents = { onDsExpandedChange: EventName<DsAccordionCustomEvent<string[]>> };

export const DsAccordion: StencilReactComponent<DsAccordionElement, DsAccordionEvents, Components.DsAccordion> = /*@__PURE__*/ createComponent<DsAccordionElement, DsAccordionEvents, Components.DsAccordion>({
    tagName: 'ds-accordion',
    elementClass: DsAccordionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsExpandedChange: 'dsExpandedChange' } as DsAccordionEvents,
    defineCustomElement: defineDsAccordion
});
