'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsAttachmentList as DsAttachmentListElement, defineCustomElement as defineDsAttachmentList } from "@ds-mo/ui/dist/components/ds-attachment-list.js";

export type DsAttachmentListEvents = NonNullable<unknown>;

export const DsAttachmentList: StencilReactComponent<DsAttachmentListElement, DsAttachmentListEvents, Components.DsAttachmentList> = /*@__PURE__*/ createComponent<DsAttachmentListElement, DsAttachmentListEvents, Components.DsAttachmentList>({
    tagName: 'ds-attachment-list',
    elementClass: DsAttachmentListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsAttachmentListEvents,
    defineCustomElement: defineDsAttachmentList
});
