'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsAgentActivity as DsAgentActivityElement, defineCustomElement as defineDsAgentActivity } from "@ds-mo/ui/dist/components/ds-agent-activity.js";

export type DsAgentActivityEvents = NonNullable<unknown>;

export const DsAgentActivity: StencilReactComponent<DsAgentActivityElement, DsAgentActivityEvents, Components.DsAgentActivity> = /*@__PURE__*/ createComponent<DsAgentActivityElement, DsAgentActivityEvents, Components.DsAgentActivity>({
    tagName: 'ds-agent-activity',
    elementClass: DsAgentActivityElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsAgentActivityEvents,
    defineCustomElement: defineDsAgentActivity
});
