'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsAgentToolCall as DsAgentToolCallElement, defineCustomElement as defineDsAgentToolCall } from "@ds-mo/ui/dist/components/ds-agent-tool-call.js";

export type DsAgentToolCallEvents = NonNullable<unknown>;

export const DsAgentToolCall: StencilReactComponent<DsAgentToolCallElement, DsAgentToolCallEvents, Components.DsAgentToolCall> = /*@__PURE__*/ createComponent<DsAgentToolCallElement, DsAgentToolCallEvents, Components.DsAgentToolCall>({
    tagName: 'ds-agent-tool-call',
    elementClass: DsAgentToolCallElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsAgentToolCallEvents,
    defineCustomElement: defineDsAgentToolCall
});
