'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsAvatar as DsAvatarElement, defineCustomElement as defineDsAvatar } from "@ds-mo/ui/dist/components/ds-avatar.js";

export type DsAvatarEvents = NonNullable<unknown>;

export const DsAvatar: StencilReactComponent<DsAvatarElement, DsAvatarEvents, Components.DsAvatar> = /*@__PURE__*/ createComponent<DsAvatarElement, DsAvatarEvents, Components.DsAvatar>({
    tagName: 'ds-avatar',
    elementClass: DsAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsAvatarEvents,
    defineCustomElement: defineDsAvatar
});
