'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsAgentSourceList as DsAgentSourceListElement, defineCustomElement as defineDsAgentSourceList } from "@ds-mo/ui/dist/components/ds-agent-source-list.js";

export type DsAgentSourceListEvents = NonNullable<unknown>;

export const DsAgentSourceList: StencilReactComponent<DsAgentSourceListElement, DsAgentSourceListEvents, Components.DsAgentSourceList> = /*@__PURE__*/ createComponent<DsAgentSourceListElement, DsAgentSourceListEvents, Components.DsAgentSourceList>({
    tagName: 'ds-agent-source-list',
    elementClass: DsAgentSourceListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsAgentSourceListEvents,
    defineCustomElement: defineDsAgentSourceList
});
