'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsButtonUnfilledIconCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsButtonUnfilledIcon as DsButtonUnfilledIconElement, defineCustomElement as defineDsButtonUnfilledIcon } from "@ds-mo/ui/dist/components/ds-button-unfilled-icon.js";

export type DsButtonUnfilledIconEvents = {
    onDsClick: EventName<DsButtonUnfilledIconCustomEvent<MouseEvent>>,
    onDsChange: EventName<DsButtonUnfilledIconCustomEvent<boolean>>
};

export const DsButtonUnfilledIcon: StencilReactComponent<DsButtonUnfilledIconElement, DsButtonUnfilledIconEvents, Components.DsButtonUnfilledIcon> = /*@__PURE__*/ createComponent<DsButtonUnfilledIconElement, DsButtonUnfilledIconEvents, Components.DsButtonUnfilledIcon>({
    tagName: 'ds-button-unfilled-icon',
    elementClass: DsButtonUnfilledIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsClick: 'dsClick',
        onDsChange: 'dsChange'
    } as DsButtonUnfilledIconEvents,
    defineCustomElement: defineDsButtonUnfilledIcon
});
