'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsBarNavActionCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsBarNavAction as DsBarNavActionElement, defineCustomElement as defineDsBarNavAction } from "@ds-mo/ui/dist/components/ds-bar-nav-action.js";

export type DsBarNavActionEvents = { onDsChange: EventName<DsBarNavActionCustomEvent<boolean>> };

export const DsBarNavAction: StencilReactComponent<DsBarNavActionElement, DsBarNavActionEvents, Components.DsBarNavAction> = /*@__PURE__*/ createComponent<DsBarNavActionElement, DsBarNavActionEvents, Components.DsBarNavAction>({
    tagName: 'ds-bar-nav-action',
    elementClass: DsBarNavActionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsBarNavActionEvents,
    defineCustomElement: defineDsBarNavAction
});
