'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsBarNavCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsBarNav as DsBarNavElement, defineCustomElement as defineDsBarNav } from "@ds-mo/ui/dist/components/ds-bar-nav.js";

export type DsBarNavEvents = {
    onDsTabChange: EventName<DsBarNavCustomEvent<string>>,
    onDsActionChange: EventName<DsBarNavCustomEvent<{ id: string; selected: boolean }>>
};

export const DsBarNav: StencilReactComponent<DsBarNavElement, DsBarNavEvents, Components.DsBarNav> = /*@__PURE__*/ createComponent<DsBarNavElement, DsBarNavEvents, Components.DsBarNav>({
    tagName: 'ds-bar-nav',
    elementClass: DsBarNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsTabChange: 'dsTabChange',
        onDsActionChange: 'dsActionChange'
    } as DsBarNavEvents,
    defineCustomElement: defineDsBarNav
});
