'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsBarWorkflowCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsBarWorkflow as DsBarWorkflowElement, defineCustomElement as defineDsBarWorkflow } from "@ds-mo/ui/dist/components/ds-bar-workflow.js";

export type DsBarWorkflowEvents = {
    onDsExit: EventName<DsBarWorkflowCustomEvent<MouseEvent>>,
    onDsStepChange: EventName<DsBarWorkflowCustomEvent<string>>,
    onDsSubmit: EventName<DsBarWorkflowCustomEvent<MouseEvent>>
};

export const DsBarWorkflow: StencilReactComponent<DsBarWorkflowElement, DsBarWorkflowEvents, Components.DsBarWorkflow, 'heading'> = /*@__PURE__*/ createComponent<DsBarWorkflowElement, DsBarWorkflowEvents, Components.DsBarWorkflow, 'heading'>({
    tagName: 'ds-bar-workflow',
    elementClass: DsBarWorkflowElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsExit: 'dsExit',
        onDsStepChange: 'dsStepChange',
        onDsSubmit: 'dsSubmit'
    } as DsBarWorkflowEvents,
    defineCustomElement: defineDsBarWorkflow
});
