'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type BreadcrumbSelectDetail, type DsBreadcrumbCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsBreadcrumb as DsBreadcrumbElement, defineCustomElement as defineDsBreadcrumb } from "@ds-mo/ui/dist/components/ds-breadcrumb.js";

export type DsBreadcrumbEvents = { onDsSelect: EventName<DsBreadcrumbCustomEvent<BreadcrumbSelectDetail>> };

export const DsBreadcrumb: StencilReactComponent<DsBreadcrumbElement, DsBreadcrumbEvents, Components.DsBreadcrumb> = /*@__PURE__*/ createComponent<DsBreadcrumbElement, DsBreadcrumbEvents, Components.DsBreadcrumb>({
    tagName: 'ds-breadcrumb',
    elementClass: DsBreadcrumbElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsSelect: 'dsSelect' } as DsBreadcrumbEvents,
    defineCustomElement: defineDsBreadcrumb
});
