'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsBannerCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsBanner as DsBannerElement, defineCustomElement as defineDsBanner } from "@ds-mo/ui/dist/components/ds-banner.js";

export type DsBannerEvents = { onDsDismiss: EventName<DsBannerCustomEvent<void>> };

export const DsBanner: StencilReactComponent<DsBannerElement, DsBannerEvents, Components.DsBanner> = /*@__PURE__*/ createComponent<DsBannerElement, DsBannerEvents, Components.DsBanner>({
    tagName: 'ds-banner',
    elementClass: DsBannerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsDismiss: 'dsDismiss' } as DsBannerEvents,
    defineCustomElement: defineDsBanner
});
