'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsButtonCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsButton as DsButtonElement, defineCustomElement as defineDsButton } from "@ds-mo/ui/dist/components/ds-button.js";

export type DsButtonEvents = {
    onDsClick: EventName<DsButtonCustomEvent<MouseEvent>>,
    onDsMouseEnter: EventName<DsButtonCustomEvent<MouseEvent>>,
    onDsMouseLeave: EventName<DsButtonCustomEvent<MouseEvent>>
};

export const DsButton: StencilReactComponent<DsButtonElement, DsButtonEvents, Components.DsButton> = /*@__PURE__*/ createComponent<DsButtonElement, DsButtonEvents, Components.DsButton>({
    tagName: 'ds-button',
    elementClass: DsButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsClick: 'dsClick',
        onDsMouseEnter: 'dsMouseEnter',
        onDsMouseLeave: 'dsMouseLeave'
    } as DsButtonEvents,
    defineCustomElement: defineDsButton
});
