'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type BreadcrumbSelectDetail, type DsBarTitleCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsBarTitle as DsBarTitleElement, defineCustomElement as defineDsBarTitle } from "@ds-mo/ui/dist/components/ds-bar-title.js";

export type DsBarTitleEvents = {
    onDsBack: EventName<DsBarTitleCustomEvent<MouseEvent>>,
    onDsBreadcrumbSelect: EventName<DsBarTitleCustomEvent<BreadcrumbSelectDetail>>,
    onDsSectionChange: EventName<DsBarTitleCustomEvent<string>>,
    onDsAction: EventName<DsBarTitleCustomEvent<string>>
};

export const DsBarTitle: StencilReactComponent<DsBarTitleElement, DsBarTitleEvents, Components.DsBarTitle, 'heading'> = /*@__PURE__*/ createComponent<DsBarTitleElement, DsBarTitleEvents, Components.DsBarTitle, 'heading'>({
    tagName: 'ds-bar-title',
    elementClass: DsBarTitleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsBack: 'dsBack',
        onDsBreadcrumbSelect: 'dsBreadcrumbSelect',
        onDsSectionChange: 'dsSectionChange',
        onDsAction: 'dsAction'
    } as DsBarTitleEvents,
    defineCustomElement: defineDsBarTitle
});
