'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsButtonUnfilledCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsButtonUnfilled as DsButtonUnfilledElement, defineCustomElement as defineDsButtonUnfilled } from "@ds-mo/ui/dist/components/ds-button-unfilled.js";

export type DsButtonUnfilledEvents = {
    onDsClick: EventName<DsButtonUnfilledCustomEvent<MouseEvent>>,
    onDsChange: EventName<DsButtonUnfilledCustomEvent<boolean>>
};

export const DsButtonUnfilled: StencilReactComponent<DsButtonUnfilledElement, DsButtonUnfilledEvents, Components.DsButtonUnfilled> = /*@__PURE__*/ createComponent<DsButtonUnfilledElement, DsButtonUnfilledEvents, Components.DsButtonUnfilled>({
    tagName: 'ds-button-unfilled',
    elementClass: DsButtonUnfilledElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsClick: 'dsClick',
        onDsChange: 'dsChange'
    } as DsButtonUnfilledEvents,
    defineCustomElement: defineDsButtonUnfilled
});
