'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsBadge as DsBadgeElement, defineCustomElement as defineDsBadge } from "@ds-mo/ui/dist/components/ds-badge.js";

export type DsBadgeEvents = NonNullable<unknown>;

export const DsBadge: StencilReactComponent<DsBadgeElement, DsBadgeEvents, Components.DsBadge> = /*@__PURE__*/ createComponent<DsBadgeElement, DsBadgeEvents, Components.DsBadge>({
    tagName: 'ds-badge',
    elementClass: DsBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsBadgeEvents,
    defineCustomElement: defineDsBadge
});
