'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsButtonFilledCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsButtonFilled as DsButtonFilledElement, defineCustomElement as defineDsButtonFilled } from "@ds-mo/ui/dist/components/ds-button-filled.js";

export type DsButtonFilledEvents = { onDsClick: EventName<DsButtonFilledCustomEvent<MouseEvent>> };

export const DsButtonFilled: StencilReactComponent<DsButtonFilledElement, DsButtonFilledEvents, Components.DsButtonFilled> = /*@__PURE__*/ createComponent<DsButtonFilledElement, DsButtonFilledEvents, Components.DsButtonFilled>({
    tagName: 'ds-button-filled',
    elementClass: DsButtonFilledElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsClick: 'dsClick' } as DsButtonFilledEvents,
    defineCustomElement: defineDsButtonFilled
});
