'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsConversationList as DsConversationListElement, defineCustomElement as defineDsConversationList } from "@ds-mo/ui/dist/components/ds-conversation-list.js";

export type DsConversationListEvents = NonNullable<unknown>;

export const DsConversationList: StencilReactComponent<DsConversationListElement, DsConversationListEvents, Components.DsConversationList> = /*@__PURE__*/ createComponent<DsConversationListElement, DsConversationListEvents, Components.DsConversationList>({
    tagName: 'ds-conversation-list',
    elementClass: DsConversationListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsConversationListEvents,
    defineCustomElement: defineDsConversationList
});
