'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ChartDatum, type DsChartDonutCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsChartDonut as DsChartDonutElement, defineCustomElement as defineDsChartDonut } from "@ds-mo/ui/dist/components/ds-chart-donut.js";

export type DsChartDonutEvents = { onDsSliceHover: EventName<DsChartDonutCustomEvent<ChartDatum | null>> };

export const DsChartDonut: StencilReactComponent<DsChartDonutElement, DsChartDonutEvents, Components.DsChartDonut> = /*@__PURE__*/ createComponent<DsChartDonutElement, DsChartDonutEvents, Components.DsChartDonut>({
    tagName: 'ds-chart-donut',
    elementClass: DsChartDonutElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsSliceHover: 'dsSliceHover' } as DsChartDonutEvents,
    defineCustomElement: defineDsChartDonut
});
