'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ChartLegendItem, type DsChartLegendCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsChartLegend as DsChartLegendElement, defineCustomElement as defineDsChartLegend } from "@ds-mo/ui/dist/components/ds-chart-legend.js";

export type DsChartLegendEvents = {
    onDsItemHover: EventName<DsChartLegendCustomEvent<ChartLegendItem | null>>,
    onDsItemClick: EventName<DsChartLegendCustomEvent<{ item: ChartLegendItem; originalEvent: MouseEvent }>>
};

export const DsChartLegend: StencilReactComponent<DsChartLegendElement, DsChartLegendEvents, Components.DsChartLegend> = /*@__PURE__*/ createComponent<DsChartLegendElement, DsChartLegendEvents, Components.DsChartLegend>({
    tagName: 'ds-chart-legend',
    elementClass: DsChartLegendElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsItemHover: 'dsItemHover',
        onDsItemClick: 'dsItemClick'
    } as DsChartLegendEvents,
    defineCustomElement: defineDsChartLegend
});
