'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsCodeBlock as DsCodeBlockElement, defineCustomElement as defineDsCodeBlock } from "@ds-mo/ui/dist/components/ds-code-block.js";

export type DsCodeBlockEvents = NonNullable<unknown>;

export const DsCodeBlock: StencilReactComponent<DsCodeBlockElement, DsCodeBlockEvents, Components.DsCodeBlock> = /*@__PURE__*/ createComponent<DsCodeBlockElement, DsCodeBlockEvents, Components.DsCodeBlock>({
    tagName: 'ds-code-block',
    elementClass: DsCodeBlockElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsCodeBlockEvents,
    defineCustomElement: defineDsCodeBlock
});
