'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsCardDataVizBarCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsCardDataVizBar as DsCardDataVizBarElement, defineCustomElement as defineDsCardDataVizBar } from "@ds-mo/ui/dist/components/ds-card-data-viz-bar.js";

export type DsCardDataVizBarEvents = { onDsFilterClick: EventName<DsCardDataVizBarCustomEvent<void>> };

export const DsCardDataVizBar: StencilReactComponent<DsCardDataVizBarElement, DsCardDataVizBarEvents, Components.DsCardDataVizBar, 'heading'> = /*@__PURE__*/ createComponent<DsCardDataVizBarElement, DsCardDataVizBarEvents, Components.DsCardDataVizBar, 'heading'>({
    tagName: 'ds-card-data-viz-bar',
    elementClass: DsCardDataVizBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsFilterClick: 'dsFilterClick' } as DsCardDataVizBarEvents,
    defineCustomElement: defineDsCardDataVizBar
});
