'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsConversationListItemCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsConversationListItem as DsConversationListItemElement, defineCustomElement as defineDsConversationListItem } from "@ds-mo/ui/dist/components/ds-conversation-list-item.js";

export type DsConversationListItemEvents = { onDsSelect: EventName<DsConversationListItemCustomEvent<{ id: string }>> };

export const DsConversationListItem: StencilReactComponent<DsConversationListItemElement, DsConversationListItemEvents, Components.DsConversationListItem> = /*@__PURE__*/ createComponent<DsConversationListItemElement, DsConversationListItemEvents, Components.DsConversationListItem>({
    tagName: 'ds-conversation-list-item',
    elementClass: DsConversationListItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsSelect: 'dsSelect' } as DsConversationListItemEvents,
    defineCustomElement: defineDsConversationListItem
});
