'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsConversationListSection as DsConversationListSectionElement, defineCustomElement as defineDsConversationListSection } from "@ds-mo/ui/dist/components/ds-conversation-list-section.js";

export type DsConversationListSectionEvents = NonNullable<unknown>;

export const DsConversationListSection: StencilReactComponent<DsConversationListSectionElement, DsConversationListSectionEvents, Components.DsConversationListSection> = /*@__PURE__*/ createComponent<DsConversationListSectionElement, DsConversationListSectionEvents, Components.DsConversationListSection>({
    tagName: 'ds-conversation-list-section',
    elementClass: DsConversationListSectionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsConversationListSectionEvents,
    defineCustomElement: defineDsConversationListSection
});
