'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsCheckboxCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsCheckbox as DsCheckboxElement, defineCustomElement as defineDsCheckbox } from "@ds-mo/ui/dist/components/ds-checkbox.js";

export type DsCheckboxEvents = { onDsChange: EventName<DsCheckboxCustomEvent<boolean>> };

export const DsCheckbox: StencilReactComponent<DsCheckboxElement, DsCheckboxEvents, Components.DsCheckbox, 'label'> = /*@__PURE__*/ createComponent<DsCheckboxElement, DsCheckboxEvents, Components.DsCheckbox, 'label'>({
    tagName: 'ds-checkbox',
    elementClass: DsCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsCheckboxEvents,
    defineCustomElement: defineDsCheckbox
});
