'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsCardShellDataViz as DsCardShellDataVizElement, defineCustomElement as defineDsCardShellDataViz } from "@ds-mo/ui/dist/components/ds-card-shell-data-viz.js";

export type DsCardShellDataVizEvents = NonNullable<unknown>;

export const DsCardShellDataViz: StencilReactComponent<DsCardShellDataVizElement, DsCardShellDataVizEvents, Components.DsCardShellDataViz, 'heading'> = /*@__PURE__*/ createComponent<DsCardShellDataVizElement, DsCardShellDataVizEvents, Components.DsCardShellDataViz, 'heading'>({
    tagName: 'ds-card-shell-data-viz',
    elementClass: DsCardShellDataVizElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsCardShellDataVizEvents,
    defineCustomElement: defineDsCardShellDataViz
});
