'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsCardDataVizLineCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsCardDataVizLine as DsCardDataVizLineElement, defineCustomElement as defineDsCardDataVizLine } from "@ds-mo/ui/dist/components/ds-card-data-viz-line.js";

export type DsCardDataVizLineEvents = { onDsFilterClick: EventName<DsCardDataVizLineCustomEvent<void>> };

export const DsCardDataVizLine: StencilReactComponent<DsCardDataVizLineElement, DsCardDataVizLineEvents, Components.DsCardDataVizLine, 'heading'> = /*@__PURE__*/ createComponent<DsCardDataVizLineElement, DsCardDataVizLineEvents, Components.DsCardDataVizLine, 'heading'>({
    tagName: 'ds-card-data-viz-line',
    elementClass: DsCardDataVizLineElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsFilterClick: 'dsFilterClick' } as DsCardDataVizLineEvents,
    defineCustomElement: defineDsCardDataVizLine
});
