'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsCard as DsCardElement, defineCustomElement as defineDsCard } from "@ds-mo/ui/dist/components/ds-card.js";

export type DsCardEvents = NonNullable<unknown>;

export const DsCard: StencilReactComponent<DsCardElement, DsCardEvents, Components.DsCard, 'heading'> = /*@__PURE__*/ createComponent<DsCardElement, DsCardEvents, Components.DsCard, 'heading'>({
    tagName: 'ds-card',
    elementClass: DsCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsCardEvents,
    defineCustomElement: defineDsCard
});
