'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsCardOverviewCustomEvent, type OverviewMetric } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsCardOverview as DsCardOverviewElement, defineCustomElement as defineDsCardOverview } from "@ds-mo/ui/dist/components/ds-card-overview.js";

export type DsCardOverviewEvents = { onDsMetricSelect: EventName<DsCardOverviewCustomEvent<OverviewMetric>> };

export const DsCardOverview: StencilReactComponent<DsCardOverviewElement, DsCardOverviewEvents, Components.DsCardOverview> = /*@__PURE__*/ createComponent<DsCardOverviewElement, DsCardOverviewEvents, Components.DsCardOverview>({
    tagName: 'ds-card-overview',
    elementClass: DsCardOverviewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsMetricSelect: 'dsMetricSelect' } as DsCardOverviewEvents,
    defineCustomElement: defineDsCardOverview
});
