'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsChartBarStacked as DsChartBarStackedElement, defineCustomElement as defineDsChartBarStacked } from "@ds-mo/ui/dist/components/ds-chart-bar-stacked.js";

export type DsChartBarStackedEvents = NonNullable<unknown>;

export const DsChartBarStacked: StencilReactComponent<DsChartBarStackedElement, DsChartBarStackedEvents, Components.DsChartBarStacked> = /*@__PURE__*/ createComponent<DsChartBarStackedElement, DsChartBarStackedEvents, Components.DsChartBarStacked>({
    tagName: 'ds-chart-bar-stacked',
    elementClass: DsChartBarStackedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsChartBarStackedEvents,
    defineCustomElement: defineDsChartBarStacked
});
