'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsChipCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsChip as DsChipElement, defineCustomElement as defineDsChip } from "@ds-mo/ui/dist/components/ds-chip.js";

export type DsChipEvents = { onDsRemove: EventName<DsChipCustomEvent<void>> };

export const DsChip: StencilReactComponent<DsChipElement, DsChipEvents, Components.DsChip, 'label'> = /*@__PURE__*/ createComponent<DsChipElement, DsChipEvents, Components.DsChip, 'label'>({
    tagName: 'ds-chip',
    elementClass: DsChipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsRemove: 'dsRemove' } as DsChipEvents,
    defineCustomElement: defineDsChip
});
