'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsDivider as DsDividerElement, defineCustomElement as defineDsDivider } from "@ds-mo/ui/dist/components/ds-divider.js";

export type DsDividerEvents = NonNullable<unknown>;

export const DsDivider: StencilReactComponent<DsDividerElement, DsDividerEvents, Components.DsDivider> = /*@__PURE__*/ createComponent<DsDividerElement, DsDividerEvents, Components.DsDivider>({
    tagName: 'ds-divider',
    elementClass: DsDividerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsDividerEvents,
    defineCustomElement: defineDsDivider
});
