'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsEmptyState as DsEmptyStateElement, defineCustomElement as defineDsEmptyState } from "@ds-mo/ui/dist/components/ds-empty-state.js";

export type DsEmptyStateEvents = NonNullable<unknown>;

export const DsEmptyState: StencilReactComponent<DsEmptyStateElement, DsEmptyStateEvents, Components.DsEmptyState> = /*@__PURE__*/ createComponent<DsEmptyStateElement, DsEmptyStateEvents, Components.DsEmptyState>({
    tagName: 'ds-empty-state',
    elementClass: DsEmptyStateElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsEmptyStateEvents,
    defineCustomElement: defineDsEmptyState
});
