'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsFade as DsFadeElement, defineCustomElement as defineDsFade } from "@ds-mo/ui/dist/components/ds-fade.js";

export type DsFadeEvents = NonNullable<unknown>;

export const DsFade: StencilReactComponent<DsFadeElement, DsFadeEvents, Components.DsFade> = /*@__PURE__*/ createComponent<DsFadeElement, DsFadeEvents, Components.DsFade>({
    tagName: 'ds-fade',
    elementClass: DsFadeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsFadeEvents,
    defineCustomElement: defineDsFade
});
