'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsField as DsFieldElement, defineCustomElement as defineDsField } from "@ds-mo/ui/dist/components/ds-field.js";

export type DsFieldEvents = NonNullable<unknown>;

export const DsField: StencilReactComponent<DsFieldElement, DsFieldEvents, Components.DsField, 'label'> = /*@__PURE__*/ createComponent<DsFieldElement, DsFieldEvents, Components.DsField, 'label'>({
    tagName: 'ds-field',
    elementClass: DsFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsFieldEvents,
    defineCustomElement: defineDsField
});
