'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsIcon as DsIconElement, defineCustomElement as defineDsIcon } from "@ds-mo/ui/dist/components/ds-icon.js";

export type DsIconEvents = NonNullable<unknown>;

export const DsIcon: StencilReactComponent<DsIconElement, DsIconEvents, Components.DsIcon> = /*@__PURE__*/ createComponent<DsIconElement, DsIconEvents, Components.DsIcon>({
    tagName: 'ds-icon',
    elementClass: DsIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsIconEvents,
    defineCustomElement: defineDsIcon
});
