'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsInputCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsInput as DsInputElement, defineCustomElement as defineDsInput } from "@ds-mo/ui/dist/components/ds-input.js";

export type DsInputEvents = {
    onDsChange: EventName<DsInputCustomEvent<string>>,
    onDsClear: EventName<DsInputCustomEvent<void>>
};

export const DsInput: StencilReactComponent<DsInputElement, DsInputEvents, Components.DsInput> = /*@__PURE__*/ createComponent<DsInputElement, DsInputEvents, Components.DsInput>({
    tagName: 'ds-input',
    elementClass: DsInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsChange: 'dsChange',
        onDsClear: 'dsClear'
    } as DsInputEvents,
    defineCustomElement: defineDsInput
});
