'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsLoader as DsLoaderElement, defineCustomElement as defineDsLoader } from "@ds-mo/ui/dist/components/ds-loader.js";

export type DsLoaderEvents = NonNullable<unknown>;

export const DsLoader: StencilReactComponent<DsLoaderElement, DsLoaderEvents, Components.DsLoader> = /*@__PURE__*/ createComponent<DsLoaderElement, DsLoaderEvents, Components.DsLoader>({
    tagName: 'ds-loader',
    elementClass: DsLoaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsLoaderEvents,
    defineCustomElement: defineDsLoader
});
