'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsLabelWrap as DsLabelWrapElement, defineCustomElement as defineDsLabelWrap } from "@ds-mo/ui/dist/components/ds-label-wrap.js";

export type DsLabelWrapEvents = NonNullable<unknown>;

export const DsLabelWrap: StencilReactComponent<DsLabelWrapElement, DsLabelWrapEvents, Components.DsLabelWrap> = /*@__PURE__*/ createComponent<DsLabelWrapElement, DsLabelWrapEvents, Components.DsLabelWrap>({
    tagName: 'ds-label-wrap',
    elementClass: DsLabelWrapElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsLabelWrapEvents,
    defineCustomElement: defineDsLabelWrap
});
