'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsMessageComposerCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsMessageComposer as DsMessageComposerElement, defineCustomElement as defineDsMessageComposer } from "@ds-mo/ui/dist/components/ds-message-composer.js";

export type DsMessageComposerEvents = {
    onDsInput: EventName<DsMessageComposerCustomEvent<string>>,
    onDsSubmit: EventName<DsMessageComposerCustomEvent<{ text: string }>>,
    onDsStop: EventName<DsMessageComposerCustomEvent<void>>
};

export const DsMessageComposer: StencilReactComponent<DsMessageComposerElement, DsMessageComposerEvents, Components.DsMessageComposer> = /*@__PURE__*/ createComponent<DsMessageComposerElement, DsMessageComposerEvents, Components.DsMessageComposer>({
    tagName: 'ds-message-composer',
    elementClass: DsMessageComposerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsInput: 'dsInput',
        onDsSubmit: 'dsSubmit',
        onDsStop: 'dsStop'
    } as DsMessageComposerEvents,
    defineCustomElement: defineDsMessageComposer
});
