'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsMessage as DsMessageElement, defineCustomElement as defineDsMessage } from "@ds-mo/ui/dist/components/ds-message.js";

export type DsMessageEvents = NonNullable<unknown>;

export const DsMessage: StencilReactComponent<DsMessageElement, DsMessageEvents, Components.DsMessage> = /*@__PURE__*/ createComponent<DsMessageElement, DsMessageEvents, Components.DsMessage>({
    tagName: 'ds-message',
    elementClass: DsMessageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsMessageEvents,
    defineCustomElement: defineDsMessage
});
