'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsMobileHeaderCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsMobileHeader as DsMobileHeaderElement, defineCustomElement as defineDsMobileHeader } from "@ds-mo/ui/dist/components/ds-mobile-header.js";

export type DsMobileHeaderEvents = {
    onDsSectionChange: EventName<DsMobileHeaderCustomEvent<string>>,
    onDsSubsectionChange: EventName<DsMobileHeaderCustomEvent<string>>
};

export const DsMobileHeader: StencilReactComponent<DsMobileHeaderElement, DsMobileHeaderEvents, Components.DsMobileHeader> = /*@__PURE__*/ createComponent<DsMobileHeaderElement, DsMobileHeaderEvents, Components.DsMobileHeader>({
    tagName: 'ds-mobile-header',
    elementClass: DsMobileHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsSectionChange: 'dsSectionChange',
        onDsSubsectionChange: 'dsSubsectionChange'
    } as DsMobileHeaderEvents,
    defineCustomElement: defineDsMobileHeader
});
