'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsMobileSectionSwitcherCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsMobileSectionSwitcher as DsMobileSectionSwitcherElement, defineCustomElement as defineDsMobileSectionSwitcher } from "@ds-mo/ui/dist/components/ds-mobile-section-switcher.js";

export type DsMobileSectionSwitcherEvents = { onDsChange: EventName<DsMobileSectionSwitcherCustomEvent<string>> };

export const DsMobileSectionSwitcher: StencilReactComponent<DsMobileSectionSwitcherElement, DsMobileSectionSwitcherEvents, Components.DsMobileSectionSwitcher> = /*@__PURE__*/ createComponent<DsMobileSectionSwitcherElement, DsMobileSectionSwitcherEvents, Components.DsMobileSectionSwitcher>({
    tagName: 'ds-mobile-section-switcher',
    elementClass: DsMobileSectionSwitcherElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsMobileSectionSwitcherEvents,
    defineCustomElement: defineDsMobileSectionSwitcher
});
