'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsMessageBubble as DsMessageBubbleElement, defineCustomElement as defineDsMessageBubble } from "@ds-mo/ui/dist/components/ds-message-bubble.js";

export type DsMessageBubbleEvents = NonNullable<unknown>;

export const DsMessageBubble: StencilReactComponent<DsMessageBubbleElement, DsMessageBubbleEvents, Components.DsMessageBubble> = /*@__PURE__*/ createComponent<DsMessageBubbleElement, DsMessageBubbleEvents, Components.DsMessageBubble>({
    tagName: 'ds-message-bubble',
    elementClass: DsMessageBubbleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsMessageBubbleEvents,
    defineCustomElement: defineDsMessageBubble
});
