'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsMessageScrollerCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsMessageScroller as DsMessageScrollerElement, defineCustomElement as defineDsMessageScroller } from "@ds-mo/ui/dist/components/ds-message-scroller.js";

export type DsMessageScrollerEvents = { onDsReachStart: EventName<DsMessageScrollerCustomEvent<void>> };

export const DsMessageScroller: StencilReactComponent<DsMessageScrollerElement, DsMessageScrollerEvents, Components.DsMessageScroller> = /*@__PURE__*/ createComponent<DsMessageScrollerElement, DsMessageScrollerEvents, Components.DsMessageScroller>({
    tagName: 'ds-message-scroller',
    elementClass: DsMessageScrollerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsReachStart: 'dsReachStart' } as DsMessageScrollerEvents,
    defineCustomElement: defineDsMessageScroller
});
