'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsMarkdown as DsMarkdownElement, defineCustomElement as defineDsMarkdown } from "@ds-mo/ui/dist/components/ds-markdown.js";

export type DsMarkdownEvents = NonNullable<unknown>;

export const DsMarkdown: StencilReactComponent<DsMarkdownElement, DsMarkdownEvents, Components.DsMarkdown> = /*@__PURE__*/ createComponent<DsMarkdownElement, DsMarkdownEvents, Components.DsMarkdown>({
    tagName: 'ds-markdown',
    elementClass: DsMarkdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsMarkdownEvents,
    defineCustomElement: defineDsMarkdown
});
