'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsMobileBarNavCustomEvent, type MobileBarNavDestinationDetail } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsMobileBarNav as DsMobileBarNavElement, defineCustomElement as defineDsMobileBarNav } from "@ds-mo/ui/dist/components/ds-mobile-bar-nav.js";

export type DsMobileBarNavEvents = {
    onDsSheetNavToggle: EventName<DsMobileBarNavCustomEvent<boolean>>,
    onDsDestinationChange: EventName<DsMobileBarNavCustomEvent<MobileBarNavDestinationDetail>>
};

export const DsMobileBarNav: StencilReactComponent<DsMobileBarNavElement, DsMobileBarNavEvents, Components.DsMobileBarNav> = /*@__PURE__*/ createComponent<DsMobileBarNavElement, DsMobileBarNavEvents, Components.DsMobileBarNav>({
    tagName: 'ds-mobile-bar-nav',
    elementClass: DsMobileBarNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsSheetNavToggle: 'dsSheetNavToggle',
        onDsDestinationChange: 'dsDestinationChange'
    } as DsMobileBarNavEvents,
    defineCustomElement: defineDsMobileBarNav
});
