'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsMobileSheetNavCustomEvent, type NavChromeStyle } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsMobileSheetNav as DsMobileSheetNavElement, defineCustomElement as defineDsMobileSheetNav } from "@ds-mo/ui/dist/components/ds-mobile-sheet-nav.js";

export type DsMobileSheetNavEvents = {
    onDsAreaSelect: EventName<DsMobileSheetNavCustomEvent<string>>,
    onDsBrowseContextChange: EventName<DsMobileSheetNavCustomEvent<NavChromeStyle>>,
    onDsClose: EventName<DsMobileSheetNavCustomEvent<void>>
};

export const DsMobileSheetNav: StencilReactComponent<DsMobileSheetNavElement, DsMobileSheetNavEvents, Components.DsMobileSheetNav> = /*@__PURE__*/ createComponent<DsMobileSheetNavElement, DsMobileSheetNavEvents, Components.DsMobileSheetNav>({
    tagName: 'ds-mobile-sheet-nav',
    elementClass: DsMobileSheetNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsAreaSelect: 'dsAreaSelect',
        onDsBrowseContextChange: 'dsBrowseContextChange',
        onDsClose: 'dsClose'
    } as DsMobileSheetNavEvents,
    defineCustomElement: defineDsMobileSheetNav
});
