'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsMenuCustomEvent, type MenuItemData } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsMenu as DsMenuElement, defineCustomElement as defineDsMenu } from "@ds-mo/ui/dist/components/ds-menu.js";

export type DsMenuEvents = {
    onDsClose: EventName<DsMenuCustomEvent<void>>,
    onDsSelect: EventName<DsMenuCustomEvent<MenuItemData>>
};

export const DsMenu: StencilReactComponent<DsMenuElement, DsMenuEvents, Components.DsMenu> = /*@__PURE__*/ createComponent<DsMenuElement, DsMenuEvents, Components.DsMenu>({
    tagName: 'ds-menu',
    elementClass: DsMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsClose: 'dsClose',
        onDsSelect: 'dsSelect'
    } as DsMenuEvents,
    defineCustomElement: defineDsMenu
});
