'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ChromeTransitionDetail, type DsPanelToolsCustomEvent, type PanelToolsToolId } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsPanelTools as DsPanelToolsElement, defineCustomElement as defineDsPanelTools } from "@ds-mo/ui/dist/components/ds-panel-tools.js";

export type DsPanelToolsEvents = {
    onDsToolChange: EventName<DsPanelToolsCustomEvent<{ id: PanelToolsToolId; selected: boolean; }>>,
    onDsPresentationChange: EventName<DsPanelToolsCustomEvent<{ presentation: 'drawer' | 'fullscreen'; }>>,
    onDsHeaderBack: EventName<DsPanelToolsCustomEvent<{ tool: PanelToolsToolId; }>>,
    onDsHeaderAction: EventName<DsPanelToolsCustomEvent<{ tool: PanelToolsToolId; id: string; }>>,
    onDsChromeTransitionStart: EventName<DsPanelToolsCustomEvent<ChromeTransitionDetail>>,
    onDsChromeTransitionEnd: EventName<DsPanelToolsCustomEvent<ChromeTransitionDetail>>
};

export const DsPanelTools: StencilReactComponent<DsPanelToolsElement, DsPanelToolsEvents, Components.DsPanelTools> = /*@__PURE__*/ createComponent<DsPanelToolsElement, DsPanelToolsEvents, Components.DsPanelTools>({
    tagName: 'ds-panel-tools',
    elementClass: DsPanelToolsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsToolChange: 'dsToolChange',
        onDsPresentationChange: 'dsPresentationChange',
        onDsHeaderBack: 'dsHeaderBack',
        onDsHeaderAction: 'dsHeaderAction',
        onDsChromeTransitionStart: 'dsChromeTransitionStart',
        onDsChromeTransitionEnd: 'dsChromeTransitionEnd'
    } as DsPanelToolsEvents,
    defineCustomElement: defineDsPanelTools
});
