'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsPanelToolSearchCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsPanelToolSearch as DsPanelToolSearchElement, defineCustomElement as defineDsPanelToolSearch } from "@ds-mo/ui/dist/components/ds-panel-tool-search.js";

export type DsPanelToolSearchEvents = {
    onDsChange: EventName<DsPanelToolSearchCustomEvent<string>>,
    onDsClear: EventName<DsPanelToolSearchCustomEvent<void>>,
    onDsFilterToggle: EventName<DsPanelToolSearchCustomEvent<MouseEvent>>
};

export const DsPanelToolSearch: StencilReactComponent<DsPanelToolSearchElement, DsPanelToolSearchEvents, Components.DsPanelToolSearch> = /*@__PURE__*/ createComponent<DsPanelToolSearchElement, DsPanelToolSearchEvents, Components.DsPanelToolSearch>({
    tagName: 'ds-panel-tool-search',
    elementClass: DsPanelToolSearchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsChange: 'dsChange',
        onDsClear: 'dsClear',
        onDsFilterToggle: 'dsFilterToggle'
    } as DsPanelToolSearchEvents,
    defineCustomElement: defineDsPanelToolSearch
});
