'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsPaginationCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsPagination as DsPaginationElement, defineCustomElement as defineDsPagination } from "@ds-mo/ui/dist/components/ds-pagination.js";

export type DsPaginationEvents = { onDsPageChange: EventName<DsPaginationCustomEvent<number>> };

export const DsPagination: StencilReactComponent<DsPaginationElement, DsPaginationEvents, Components.DsPagination> = /*@__PURE__*/ createComponent<DsPaginationElement, DsPaginationEvents, Components.DsPagination>({
    tagName: 'ds-pagination',
    elementClass: DsPaginationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsPageChange: 'dsPageChange' } as DsPaginationEvents,
    defineCustomElement: defineDsPagination
});
