'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ChromeTransitionDetail, type DsPanelNavCustomEvent, type PanelNavUserActionDetail } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsPanelNav as DsPanelNavElement, defineCustomElement as defineDsPanelNav } from "@ds-mo/ui/dist/components/ds-panel-nav.js";

export type DsPanelNavEvents = {
    onDsNavSelect: EventName<DsPanelNavCustomEvent<string>>,
    onDsNavToggle: EventName<DsPanelNavCustomEvent<boolean>>,
    onDsChromeTransitionStart: EventName<DsPanelNavCustomEvent<ChromeTransitionDetail>>,
    onDsChromeTransitionEnd: EventName<DsPanelNavCustomEvent<ChromeTransitionDetail>>,
    onDsNavFooterAction: EventName<DsPanelNavCustomEvent<void>>,
    onDsNavUserAction: EventName<DsPanelNavCustomEvent<PanelNavUserActionDetail>>
};

export const DsPanelNav: StencilReactComponent<DsPanelNavElement, DsPanelNavEvents, Components.DsPanelNav> = /*@__PURE__*/ createComponent<DsPanelNavElement, DsPanelNavEvents, Components.DsPanelNav>({
    tagName: 'ds-panel-nav',
    elementClass: DsPanelNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsNavSelect: 'dsNavSelect',
        onDsNavToggle: 'dsNavToggle',
        onDsChromeTransitionStart: 'dsChromeTransitionStart',
        onDsChromeTransitionEnd: 'dsChromeTransitionEnd',
        onDsNavFooterAction: 'dsNavFooterAction',
        onDsNavUserAction: 'dsNavUserAction'
    } as DsPanelNavEvents,
    defineCustomElement: defineDsPanelNav
});
