'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsPanelSubNavCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsPanelSubNav as DsPanelSubNavElement, defineCustomElement as defineDsPanelSubNav } from "@ds-mo/ui/dist/components/ds-panel-sub-nav.js";

export type DsPanelSubNavEvents = { onDsChange: EventName<DsPanelSubNavCustomEvent<string>> };

export const DsPanelSubNav: StencilReactComponent<DsPanelSubNavElement, DsPanelSubNavEvents, Components.DsPanelSubNav> = /*@__PURE__*/ createComponent<DsPanelSubNavElement, DsPanelSubNavEvents, Components.DsPanelSubNav>({
    tagName: 'ds-panel-sub-nav',
    elementClass: DsPanelSubNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsPanelSubNavEvents,
    defineCustomElement: defineDsPanelSubNav
});
