'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsPanelToolHeaderCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsPanelToolHeader as DsPanelToolHeaderElement, defineCustomElement as defineDsPanelToolHeader } from "@ds-mo/ui/dist/components/ds-panel-tool-header.js";

export type DsPanelToolHeaderEvents = {
    onDsBack: EventName<DsPanelToolHeaderCustomEvent<MouseEvent>>,
    onDsMenuToggle: EventName<DsPanelToolHeaderCustomEvent<MouseEvent>>,
    onDsAction: EventName<DsPanelToolHeaderCustomEvent<{ id: string; originalEvent: MouseEvent }>>
};

export const DsPanelToolHeader: StencilReactComponent<DsPanelToolHeaderElement, DsPanelToolHeaderEvents, Components.DsPanelToolHeader> = /*@__PURE__*/ createComponent<DsPanelToolHeaderElement, DsPanelToolHeaderEvents, Components.DsPanelToolHeader>({
    tagName: 'ds-panel-tool-header',
    elementClass: DsPanelToolHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsBack: 'dsBack',
        onDsMenuToggle: 'dsMenuToggle',
        onDsAction: 'dsAction'
    } as DsPanelToolHeaderEvents,
    defineCustomElement: defineDsPanelToolHeader
});
