'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsRadioGroupCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsRadioGroup as DsRadioGroupElement, defineCustomElement as defineDsRadioGroup } from "@ds-mo/ui/dist/components/ds-radio-group.js";

export type DsRadioGroupEvents = { onDsChange: EventName<DsRadioGroupCustomEvent<string>> };

export const DsRadioGroup: StencilReactComponent<DsRadioGroupElement, DsRadioGroupEvents, Components.DsRadioGroup> = /*@__PURE__*/ createComponent<DsRadioGroupElement, DsRadioGroupEvents, Components.DsRadioGroup>({
    tagName: 'ds-radio-group',
    elementClass: DsRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsRadioGroupEvents,
    defineCustomElement: defineDsRadioGroup
});
