'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsRadioCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsRadio as DsRadioElement, defineCustomElement as defineDsRadio } from "@ds-mo/ui/dist/components/ds-radio.js";

export type DsRadioEvents = { onDsChange: EventName<DsRadioCustomEvent<string>> };

export const DsRadio: StencilReactComponent<DsRadioElement, DsRadioEvents, Components.DsRadio> = /*@__PURE__*/ createComponent<DsRadioElement, DsRadioEvents, Components.DsRadio>({
    tagName: 'ds-radio',
    elementClass: DsRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsRadioEvents,
    defineCustomElement: defineDsRadio
});
