'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsShellPage as DsShellPageElement, defineCustomElement as defineDsShellPage } from "@ds-mo/ui/dist/components/ds-shell-page.js";

export type DsShellPageEvents = NonNullable<unknown>;

export const DsShellPage: StencilReactComponent<DsShellPageElement, DsShellPageEvents, Components.DsShellPage> = /*@__PURE__*/ createComponent<DsShellPageElement, DsShellPageEvents, Components.DsShellPage>({
    tagName: 'ds-shell-page',
    elementClass: DsShellPageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsShellPageEvents,
    defineCustomElement: defineDsShellPage
});
