'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsShellMobileBarCustomEvent, type ShellMobileBarDestinationDetail } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsShellMobileBar as DsShellMobileBarElement, defineCustomElement as defineDsShellMobileBar } from "@ds-mo/ui/dist/components/ds-shell-mobile-bar.js";

export type DsShellMobileBarEvents = {
    onDsNavigationToggle: EventName<DsShellMobileBarCustomEvent<boolean>>,
    onDsDestinationChange: EventName<DsShellMobileBarCustomEvent<ShellMobileBarDestinationDetail>>
};

export const DsShellMobileBar: StencilReactComponent<DsShellMobileBarElement, DsShellMobileBarEvents, Components.DsShellMobileBar> = /*@__PURE__*/ createComponent<DsShellMobileBarElement, DsShellMobileBarEvents, Components.DsShellMobileBar>({
    tagName: 'ds-shell-mobile-bar',
    elementClass: DsShellMobileBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsNavigationToggle: 'dsNavigationToggle',
        onDsDestinationChange: 'dsDestinationChange'
    } as DsShellMobileBarEvents,
    defineCustomElement: defineDsShellMobileBar
});
