'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsSwitchCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsSwitch as DsSwitchElement, defineCustomElement as defineDsSwitch } from "@ds-mo/ui/dist/components/ds-switch.js";

export type DsSwitchEvents = { onDsChange: EventName<DsSwitchCustomEvent<boolean>> };

export const DsSwitch: StencilReactComponent<DsSwitchElement, DsSwitchEvents, Components.DsSwitch> = /*@__PURE__*/ createComponent<DsSwitchElement, DsSwitchEvents, Components.DsSwitch>({
    tagName: 'ds-switch',
    elementClass: DsSwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsSwitchEvents,
    defineCustomElement: defineDsSwitch
});
