'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsSidebarCustomEvent, type SidebarWidth } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsSidebar as DsSidebarElement, defineCustomElement as defineDsSidebar } from "@ds-mo/ui/dist/components/ds-sidebar.js";

export type DsSidebarEvents = {
    onDsToggle: EventName<DsSidebarCustomEvent<void>>,
    onDsWidthChange: EventName<DsSidebarCustomEvent<SidebarWidth>>
};

export const DsSidebar: StencilReactComponent<DsSidebarElement, DsSidebarEvents, Components.DsSidebar> = /*@__PURE__*/ createComponent<DsSidebarElement, DsSidebarEvents, Components.DsSidebar>({
    tagName: 'ds-sidebar',
    elementClass: DsSidebarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsToggle: 'dsToggle',
        onDsWidthChange: 'dsWidthChange'
    } as DsSidebarEvents,
    defineCustomElement: defineDsSidebar
});
