'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsShellToolsCustomEvent, type PanelToolsToolId } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsShellTools as DsShellToolsElement, defineCustomElement as defineDsShellTools } from "@ds-mo/ui/dist/components/ds-shell-tools.js";

export type DsShellToolsEvents = {
    onDsToolChange: EventName<DsShellToolsCustomEvent<{ id: PanelToolsToolId; selected: boolean; }>>,
    onDsPresentationChange: EventName<DsShellToolsCustomEvent<{ presentation: 'drawer' | 'fullscreen'; }>>,
    onDsHeaderBack: EventName<DsShellToolsCustomEvent<{ tool: PanelToolsToolId; }>>,
    onDsHeaderAction: EventName<DsShellToolsCustomEvent<{ tool: PanelToolsToolId; id: string; }>>
};

export const DsShellTools: StencilReactComponent<DsShellToolsElement, DsShellToolsEvents, Components.DsShellTools> = /*@__PURE__*/ createComponent<DsShellToolsElement, DsShellToolsEvents, Components.DsShellTools>({
    tagName: 'ds-shell-tools',
    elementClass: DsShellToolsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsToolChange: 'dsToolChange',
        onDsPresentationChange: 'dsPresentationChange',
        onDsHeaderBack: 'dsHeaderBack',
        onDsHeaderAction: 'dsHeaderAction'
    } as DsShellToolsEvents,
    defineCustomElement: defineDsShellTools
});
