'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsSettingsSectionCardCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsSettingsSectionCard as DsSettingsSectionCardElement, defineCustomElement as defineDsSettingsSectionCard } from "@ds-mo/ui/dist/components/ds-settings-section-card.js";

export type DsSettingsSectionCardEvents = { onDsEditingChange: EventName<DsSettingsSectionCardCustomEvent<boolean>> };

export const DsSettingsSectionCard: StencilReactComponent<DsSettingsSectionCardElement, DsSettingsSectionCardEvents, Components.DsSettingsSectionCard> = /*@__PURE__*/ createComponent<DsSettingsSectionCardElement, DsSettingsSectionCardEvents, Components.DsSettingsSectionCard>({
    tagName: 'ds-settings-section-card',
    elementClass: DsSettingsSectionCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsEditingChange: 'dsEditingChange' } as DsSettingsSectionCardEvents,
    defineCustomElement: defineDsSettingsSectionCard
});
