'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsShellMobileSectionNavCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsShellMobileSectionNav as DsShellMobileSectionNavElement, defineCustomElement as defineDsShellMobileSectionNav } from "@ds-mo/ui/dist/components/ds-shell-mobile-section-nav.js";

export type DsShellMobileSectionNavEvents = { onDsTabChange: EventName<DsShellMobileSectionNavCustomEvent<string>> };

export const DsShellMobileSectionNav: StencilReactComponent<DsShellMobileSectionNavElement, DsShellMobileSectionNavEvents, Components.DsShellMobileSectionNav> = /*@__PURE__*/ createComponent<DsShellMobileSectionNavElement, DsShellMobileSectionNavEvents, Components.DsShellMobileSectionNav>({
    tagName: 'ds-shell-mobile-section-nav',
    elementClass: DsShellMobileSectionNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsTabChange: 'dsTabChange' } as DsShellMobileSectionNavEvents,
    defineCustomElement: defineDsShellMobileSectionNav
});
