'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsSkeleton as DsSkeletonElement, defineCustomElement as defineDsSkeleton } from "@ds-mo/ui/dist/components/ds-skeleton.js";

export type DsSkeletonEvents = NonNullable<unknown>;

export const DsSkeleton: StencilReactComponent<DsSkeletonElement, DsSkeletonEvents, Components.DsSkeleton> = /*@__PURE__*/ createComponent<DsSkeletonElement, DsSkeletonEvents, Components.DsSkeleton>({
    tagName: 'ds-skeleton',
    elementClass: DsSkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsSkeletonEvents,
    defineCustomElement: defineDsSkeleton
});
