'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsSelectCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsSelect as DsSelectElement, defineCustomElement as defineDsSelect } from "@ds-mo/ui/dist/components/ds-select.js";

export type DsSelectEvents = { onDsChange: EventName<DsSelectCustomEvent<string>> };

export const DsSelect: StencilReactComponent<DsSelectElement, DsSelectEvents, Components.DsSelect> = /*@__PURE__*/ createComponent<DsSelectElement, DsSelectEvents, Components.DsSelect>({
    tagName: 'ds-select',
    elementClass: DsSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsSelectEvents,
    defineCustomElement: defineDsSelect
});
