'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsSwatchPickerCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsSwatchPicker as DsSwatchPickerElement, defineCustomElement as defineDsSwatchPicker } from "@ds-mo/ui/dist/components/ds-swatch-picker.js";

export type DsSwatchPickerEvents = { onDsChange: EventName<DsSwatchPickerCustomEvent<string>> };

export const DsSwatchPicker: StencilReactComponent<DsSwatchPickerElement, DsSwatchPickerEvents, Components.DsSwatchPicker> = /*@__PURE__*/ createComponent<DsSwatchPickerElement, DsSwatchPickerEvents, Components.DsSwatchPicker>({
    tagName: 'ds-swatch-picker',
    elementClass: DsSwatchPickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsSwatchPickerEvents,
    defineCustomElement: defineDsSwatchPicker
});
