'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsScrollOverlayCustomEvent, type ScrollOverlayScrollDetail } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsScrollOverlay as DsScrollOverlayElement, defineCustomElement as defineDsScrollOverlay } from "@ds-mo/ui/dist/components/ds-scroll-overlay.js";

export type DsScrollOverlayEvents = { onDsScroll: EventName<DsScrollOverlayCustomEvent<ScrollOverlayScrollDetail>> };

export const DsScrollOverlay: StencilReactComponent<DsScrollOverlayElement, DsScrollOverlayEvents, Components.DsScrollOverlay> = /*@__PURE__*/ createComponent<DsScrollOverlayElement, DsScrollOverlayEvents, Components.DsScrollOverlay>({
    tagName: 'ds-scroll-overlay',
    elementClass: DsScrollOverlayElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsScroll: 'dsScroll' } as DsScrollOverlayEvents,
    defineCustomElement: defineDsScrollOverlay
});
