'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsSelectMultiCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsSelectMulti as DsSelectMultiElement, defineCustomElement as defineDsSelectMulti } from "@ds-mo/ui/dist/components/ds-select-multi.js";

export type DsSelectMultiEvents = {
    onDsChange: EventName<DsSelectMultiCustomEvent<string[]>>,
    onDsClear: EventName<DsSelectMultiCustomEvent<void>>,
    onDsOpenChange: EventName<DsSelectMultiCustomEvent<boolean>>
};

export const DsSelectMulti: StencilReactComponent<DsSelectMultiElement, DsSelectMultiEvents, Components.DsSelectMulti> = /*@__PURE__*/ createComponent<DsSelectMultiElement, DsSelectMultiEvents, Components.DsSelectMulti>({
    tagName: 'ds-select-multi',
    elementClass: DsSelectMultiElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsChange: 'dsChange',
        onDsClear: 'dsClear',
        onDsOpenChange: 'dsOpenChange'
    } as DsSelectMultiEvents,
    defineCustomElement: defineDsSelectMulti
});
