'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsShellMobileNavCustomEvent, type NavChromeStyle, type ShellMobileNavAuxiliaryDetail } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsShellMobileNav as DsShellMobileNavElement, defineCustomElement as defineDsShellMobileNav } from "@ds-mo/ui/dist/components/ds-shell-mobile-nav.js";

export type DsShellMobileNavEvents = {
    onDsAreaSelect: EventName<DsShellMobileNavCustomEvent<string>>,
    onDsBrowseContextChange: EventName<DsShellMobileNavCustomEvent<NavChromeStyle>>,
    onDsAuxiliarySelect: EventName<DsShellMobileNavCustomEvent<ShellMobileNavAuxiliaryDetail>>,
    onDsClose: EventName<DsShellMobileNavCustomEvent<void>>
};

export const DsShellMobileNav: StencilReactComponent<DsShellMobileNavElement, DsShellMobileNavEvents, Components.DsShellMobileNav> = /*@__PURE__*/ createComponent<DsShellMobileNavElement, DsShellMobileNavEvents, Components.DsShellMobileNav>({
    tagName: 'ds-shell-mobile-nav',
    elementClass: DsShellMobileNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsAreaSelect: 'dsAreaSelect',
        onDsBrowseContextChange: 'dsBrowseContextChange',
        onDsAuxiliarySelect: 'dsAuxiliarySelect',
        onDsClose: 'dsClose'
    } as DsShellMobileNavEvents,
    defineCustomElement: defineDsShellMobileNav
});
