'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsTag as DsTagElement, defineCustomElement as defineDsTag } from "@ds-mo/ui/dist/components/ds-tag.js";

export type DsTagEvents = NonNullable<unknown>;

export const DsTag: StencilReactComponent<DsTagElement, DsTagEvents, Components.DsTag, 'label'> = /*@__PURE__*/ createComponent<DsTagElement, DsTagEvents, Components.DsTag, 'label'>({
    tagName: 'ds-tag',
    elementClass: DsTagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsTagEvents,
    defineCustomElement: defineDsTag
});
