'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsTableCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsTable as DsTableElement, defineCustomElement as defineDsTable } from "@ds-mo/ui/dist/components/ds-table.js";

export type DsTableEvents = {
    onDsSort: EventName<DsTableCustomEvent<{ columnId: string }>>,
    onDsRowClick: EventName<DsTableCustomEvent<{ row: unknown; rowIndex: number }>>,
    onDsPageChange: EventName<DsTableCustomEvent<{ pageIndex: number }>>
};

export const DsTable: StencilReactComponent<DsTableElement, DsTableEvents, Components.DsTable> = /*@__PURE__*/ createComponent<DsTableElement, DsTableEvents, Components.DsTable>({
    tagName: 'ds-table',
    elementClass: DsTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsSort: 'dsSort',
        onDsRowClick: 'dsRowClick',
        onDsPageChange: 'dsPageChange'
    } as DsTableEvents,
    defineCustomElement: defineDsTable
});
