'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsTabGroupCustomEvent } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsTabGroup as DsTabGroupElement, defineCustomElement as defineDsTabGroup } from "@ds-mo/ui/dist/components/ds-tab-group.js";

export type DsTabGroupEvents = { onDsChange: EventName<DsTabGroupCustomEvent<string>> };

export const DsTabGroup: StencilReactComponent<DsTabGroupElement, DsTabGroupEvents, Components.DsTabGroup> = /*@__PURE__*/ createComponent<DsTabGroupElement, DsTabGroupEvents, Components.DsTabGroup>({
    tagName: 'ds-tab-group',
    elementClass: DsTabGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDsChange: 'dsChange' } as DsTabGroupEvents,
    defineCustomElement: defineDsTabGroup
});
