'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsText as DsTextElement, defineCustomElement as defineDsText } from "@ds-mo/ui/dist/components/ds-text.js";

export type DsTextEvents = NonNullable<unknown>;

export const DsText: StencilReactComponent<DsTextElement, DsTextEvents, Components.DsText> = /*@__PURE__*/ createComponent<DsTextElement, DsTextEvents, Components.DsText>({
    tagName: 'ds-text',
    elementClass: DsTextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsTextEvents,
    defineCustomElement: defineDsText
});
