'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@ds-mo/ui/dist/components";
import { DsTypingIndicator as DsTypingIndicatorElement, defineCustomElement as defineDsTypingIndicator } from "@ds-mo/ui/dist/components/ds-typing-indicator.js";

export type DsTypingIndicatorEvents = NonNullable<unknown>;

export const DsTypingIndicator: StencilReactComponent<DsTypingIndicatorElement, DsTypingIndicatorEvents, Components.DsTypingIndicator> = /*@__PURE__*/ createComponent<DsTypingIndicatorElement, DsTypingIndicatorEvents, Components.DsTypingIndicator>({
    tagName: 'ds-typing-indicator',
    elementClass: DsTypingIndicatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DsTypingIndicatorEvents,
    defineCustomElement: defineDsTypingIndicator
});
