'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DsToastCustomEvent, type ToastActionEventDetail, type ToastCloseEventDetail, type ToastEventDetail } from "@ds-mo/ui";
import type { Components } from "@ds-mo/ui/dist/components";
import { DsToast as DsToastElement, defineCustomElement as defineDsToast } from "@ds-mo/ui/dist/components/ds-toast.js";

export type DsToastEvents = {
    onDsToastClose: EventName<DsToastCustomEvent<ToastCloseEventDetail>>,
    onDsToastRemove: EventName<DsToastCustomEvent<ToastEventDetail>>,
    onDsToastAction: EventName<DsToastCustomEvent<ToastActionEventDetail>>
};

export const DsToast: StencilReactComponent<DsToastElement, DsToastEvents, Components.DsToast> = /*@__PURE__*/ createComponent<DsToastElement, DsToastEvents, Components.DsToast>({
    tagName: 'ds-toast',
    elementClass: DsToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDsToastClose: 'dsToastClose',
        onDsToastRemove: 'dsToastRemove',
        onDsToastAction: 'dsToastAction'
    } as DsToastEvents,
    defineCustomElement: defineDsToast
});
