import type { Meta, StoryObj } from '@storybook/web-components';
import { html } from 'lit';
import '../../../../dist/components/ds-accordion.js';

const items = [
  { id: 'a', label: 'What is CompoMo?', content: 'CompoMo is a framework-agnostic web component design system built with Stencil.js.' },
  { id: 'b', label: 'How do I install it?', content: 'Run `npm install @ds-mo/ui` and call `defineCustomElements()` at your app entry.' },
  { id: 'c', label: 'Does it support Angular?', content: 'Yes — Angular output target proxies are auto-generated by the Stencil compiler.' },
];

const meta: Meta = {
  title: 'Layout/Accordion',
  tags: ['autodocs'],
  argTypes: {
    multiple: { control: 'boolean' },
  },
  args: { multiple: false },
};

export default meta;
type Story = StoryObj;

export const Playground: Story = {
  render: args => html`
    <div style="width: 480px">
      <ds-accordion
        .items=${items}
        ?multiple=${args['multiple']}
      ></ds-accordion>
    </div>
  `,
};

export const MultipleOpen: Story = {
  render: () => html`
    <div style="width: 480px">
      <ds-accordion .items=${items} multiple expanded-ids="a,b"></ds-accordion>
    </div>
  `,
};

export const WithInactiveItem: Story = {
  render: () => html`
    <div style="width: 480px">
      <ds-accordion .items=${[
        { id: 'a', label: 'Active item', content: 'This item is interactive.' },
        { id: 'b', label: 'Inactive item', content: 'This cannot be expanded.', inactive: true },
        { id: 'c', label: 'Another active item', content: 'This one works too.' },
      ]}></ds-accordion>
    </div>
  `,
};
