export type {
  BarTitleAction,
  BarTitleActionAppearance,
  BarTitleActionCollapse,
  BarTitleActionConfigItem,
  BarTitleActionItem,
  BarTitleActionMobile,
  BarTitleButtonAction,
  BarTitleDivider,
  BarTitleIconAction,
  BarTitleMenuAction,
  BarTitleMenuChoice,
  BarTitleMenuChoiceItem,
  BarTitleOverflowAction,
  BarTitlePrimaryActionCollapse,
  BarTitlePrimaryAction,
  BarTitleSection,
  BarTitleSectionItem,
  BarTitleSplitAction,
  BarTitlePlacement,
  BarTitleVariant,
} from './bar-title-types';
